### ISSUE TITLE
bugs in latest dev version

### ISSUE THREAD

**Issue by AmoAlireza** [Gozargah/Marzban#1289] opened 2024-09-02 17:43 UTC
in dark theme mode we have this bug for log selection:
![image](https://github.com/user-attachments/assets/2fe5bf1d-2b86-4839-a65e-09dfba2f1c86)

in node section we have this type bug:
![image](https://github.com/user-attachments/assets/3d702556-1a02-4387-86f3-cc06551c942c)

FR: also can we have option in telegram bot to do not delete limited users have data_limit_reset_strategy, like if user reached data limit and become limited the bot also include this users to be deleted.
thanks

**Comment by erfjab** [comment] 2024-09-02 18:52
Hello, for the first case, we will fix it now. For the latter, it's not a bug, you'll need to press Ctrl + F5 to fix it. For the third case, @T3ST3ST3R0N

**Comment by AmoAlireza** [comment] 2024-09-02 19:20
> Hello, for the first case, not a bug but we will fix it now. For the latter, it's not a bug, you'll need to press Ctrl + F5 to fix it. For the third case, @T3ST3ST3R0N

i do but CTRL+F5 not working + cleared cache not working too

**Comment by erfjab** [comment] 2024-09-02 20:18
They are nothing special. Wait, they will be fixed soon.

**Comment by erfjab** [comment] 2024-09-03 11:23
I checked the problem with the Telegram bot but I didn't see any problem.

**Comment by AmoAlireza** [comment] 2024-09-03 12:27
> I checked the problem with the Telegram bot but I didn't see any problem.

i try it again but this will delete the users have period usage reset, i do this steps, going to telegram bot then edit all users and using delete limited button.

can you explain how this period usage reset work? because it seem so buggy, with help of this issue https://github.com/Gozargah/Marzban/issues/921 i set the period usage reset to daily then reset the traffic and in database change the UTC time in user_usage_logs to one day before but its not working, if you explain how can i test this i would be thankful.

**Closed** 2024-10-11 04:36 UTC
Labels: T: Bug, C: Frontend, P1, C: B-TgBot, S: In Progress
