### ISSUE TITLE
`false` config in subscription after update to v0.6.0 

### ISSUE THREAD

**Issue by sbh96** [Gozargah/Marzban#1186] opened 2024-07-25 04:23 UTC
**Describe the bug**
after updating to v0.6.0 a host was added to my subscription and my configs were called `false`

**To Reproduce**

**Expected behavior**
this error caused error in loading configs and subs in my all clients .this bug is `high risk` for your all users its can down all servers please fix and push new update thanks

**Screenshots**
![Capture](https://github.com/user-attachments/assets/b6b32ae8-ebd5-4924-8367-7fed652e2e32)

**Machine details (please complete the following information):**
 - OS: ubuntu 2024

**Additional context**
in both of my servers with different time of updates, this issue generated

**Comment by M03ED** [comment] 2024-07-25 05:48
Duplicate of #1166

**Closed** 2024-07-25 05:48 UTC
Labels: bug
